version: "3.8"
services:
  #  zipkin:
  #    image: openzipkin/zipkin
  #    ports:
  #      - "9411:9411"
  #    networks:
  #      - discovery-network
  #
  #  graphite:
  #    image: graphiteapp/graphite-statsd
  #    ports:
  #      - "2003:2003"

  discovery:
    hostname: discovery_server
    build: ./platform-services/discovery
    container_name: discovery_server
    restart: always
    ports:
      - "8761:8761"

  apigateway:
    build: ./platform-services/apigateway
    container_name: api_gateway
    restart: always
    ports:
      - "8762:8762"
    depends_on:
      - discovery

  one:
    build: ./business-services/one
    container_name: one_app
    restart: always
    expose:
      - "8082"
    ports:
      - "8082:8082"
    depends_on:
      - apigateway
      - discovery

  two:
    build: ./business-services/two
    container_name: two_app
    restart: always
    expose:
      - "8083"
    ports:
      - "8083:8083"
    depends_on:
      - apigateway
      - discovery