server:
  port: 8762

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: one-service
          uri: lb://one-service
          predicates:
            - Path=/one/**
        - id: two-service
          uri: lb://two-service
          predicates:
            - Path=/two/**

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka