server:
  port: 8083

api:
  host: http://localhost:8762

spring:
  zipkin:
    enabled: true
    baseUrl: http://localhost:9411/
  application:
    name: two-service
  sleuth:
    sampler:
      probability: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka